### ISSUE TITLE
Package is not available via composer

### ISSUE THREAD

**Issue by creinhardt-on-github** [AmastyLtd/module-mage-2.4.5-fix#1]
Hello, I'm an Amasty customer and as such, I was trying to install the fix via composer. But when trying the command "composer require amasty/module-mage-2.4.5-fix", the following error message gets thrown:

In PackageDiscoveryTrait.php line 364:
Could not find a matching version of package amasty/module-mage-2.4.5-fix. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).

Do I need to get this package added to my licenses or what could be the root cause for this?

**Comment by mmihalev** [comment]
Same issue here

**Comment by edspc** [comment]
Hello @creinhardt-on-github @mmihalev!

This is a public copy of our internal repository. Originally it was available only for Amasty customers via our composer repository.
I have added this package to packagist.org. Now it should be available via the composer globally.
